FROM node:17.8.0-alpine3.15

COPY ["package-lock.json","package.json","/home/dockerizacion/src/"]

WORKDIR /home/dockerizacion/src

RUN npm install

COPY ["." , "."]

EXPOSE 3000

CMD [ "npm", "start" ]