FROM node:17.8.0-alpine3.15

COPY ["package-lock.json","package.json","/home/saffer/Desktop/Distribuidost1/"]

WORKDIR /home/saffer/Desktop/Distribuidost1/

RUN npm install

COPY ["." , "."]

EXPOSE 3000

CMD [ "npm", "start" ]