version: '3.8'

services:

  redis:
    
    image: bitnami/redis:6.0.16

    # depends_on:
    #   - database   

    ports:
      - 6379:6379

    environment:
      - ALLOW_EMPTY_PASSWORD=yes

    

    restart: always  
    
  
  app_client:

    build:
      context: /home/saffer/Desktop/Distribuidost1/node/client

      dockerfile: ./dockerfile   

    depends_on:
      - redis
      - database
      - app_server  

    restart: always

    ports:
      - 3000:3000

    # volumes:
      # - .:/home/saffer/Desktop/Distribuidost1/grpc_example/node/client/
      # - /home/saffer/Desktop/Distribuidost1/grpc_example/node/client/node_modules

    environment:
      - IP_SERVER=app_server
      - IP_REDIS=redis

  app_server:

    build:
      context: /home/saffer/Desktop/Distribuidost1/node/server

      dockerfile: ./dockerfile   

    depends_on:
      - redis
      - database  

    restart: always

    ports:
      - 50051:50051

    # volumes:
    #   - .:/home/saffer/Desktop/Distribuidost1/grpc_example/node/server
    #   - /home/saffer/Desktop/Distribuidost1/grpc_example/node/server/node_modules

    environment:

      - IP_SERVER=app_server
      - IP_DB=database
      # - POSTGRES_HOSTNAME=database
      # - POSTGRES_USER=$POSTGRESQL_USERNAME
      # - POSTGRES_PASSWORD=$POSTGRESQL_PASSWORD
      # - POSTGRES_DB=$POSTGRESQL_DATABASE

  database:

    image: bitnami/postgresql:11

    ports:
      - 5432:5432

    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

    environment:
      - POSTGRESQL_USERNAME=soyadmin
      - POSTGRESQL_DATABASE=db_tarea1
      - ALLOW_EMPTY_PASSWORD=yes
      # - POSTGRESQL_PASSWORD=111



  
      
  
