version: '3.8'

services:

  redis:
    
    image: bitnami/redis:6.0.16

    depends_on:
      - database   

    ports:
      - 6379:6379

    environment:
      - ALLOW_EMPTY_PASSWORD=yes

    volumes:
      - ./data/redis:/bitnami/redis/data

    restart: always  
    
  
  app:

    build:
      context: ./src
      dockerfile: ./dockerfile   

    depends_on:
      - redis
      - database  

    restart: always

    ports:
      - 3000:3000

    volumes:
      - .:/home/dockerizacion/src/
      - /home/dockerizacion/src/node_modules

    environment:
      - POSTGRES_HOSTNAME=database
      - POSTGRES_USER=$POSTGRESQL_USERNAME
      - POSTGRES_PASSWORD=$POSTGRESQL_PASSWORD
      - POSTGRES_DB=$POSTGRESQL_DATABASE


  database:

    image: bitnami/postgresql:11

    ports:
      - 5432:5432

    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

    environment:
      - POSTGRESQL_USERNAME=username
      - POSTGRESQL_DATABASE=tarea
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_PASSWORD=password

  
      
  
